# 服务端口号
server:
  port: 8006
# 配置RabbitMQ信息
spring:
  rabbitmq:
    addresses: 192.168.0.105
    port: 5672
    username: ztom
    password: 123456
    # 设置监听器 acknowledge 机制
    listener:
      simple:
        acknowledge-mode: manual
        # 配置一次从消息队列中获取多少条消息（即最大unacked数）
        # prefetch: 2
        #concurrency: 1