server:
  port: 8016
# 配置RabbitMQ信息
spring:
  rabbitmq:
    addresses: 192.168.0.105
    port: 5672
    username: ztom
    password: 123456
    virtual-host: /
    # 发送消息确认机制
    # publisher-returns: true
    # 开启发送确认机制
    # publisher-confirm-type: simple